version: "3.6"
services:
                
    readingemailapi:
        container_name: readingmailsapi
        ports:
            - 49180:80
        image: marlotina/mailappexercise:api
        restart: on-failure 
        
    readingemailsite:
        container_name: readingmailssite
        ports:
            - 5800:80     
        image: marlotina/mailappexercise:site
        restart: on-failure
        depends_on:
            - readingemailapi  